# Generated by Django 3.2.7 on 2021-09-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pasteleria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasteleria',
            options={'ordering': ['created'], 'verbose_name': 'pasteleria', 'verbose_name_plural': 'recetas'},
        ),
    ]
